### ISSUE TITLE
Feat: Add symbols to VSCode's Outline for easy navigation of files

### ISSUE THREAD

**Issue by EvelynTSMG** [open-goal/opengoal-vscode#325]
VSCode has an Outline:
![image](https://github.com/open-goal/opengoal-vscode/assets/96205195/870e33a3-11b1-4e06-b92b-219949731d3c)
It would be nice if this was populated by the extension for easier navigation, especially for larger files.

**Comment by xTVaser** [comment]
This requires LSP and partially AST integration and is captured here https://github.com/open-goal/opengoal-vscode/issues/256 as `Document Symbols`
