### ISSUE TITLE
syntax hi-lite: keys and symbol arent highlighted separately

### ISSUE THREAD

**Issue by ManDude** [open-goal/opengoal-vscode#65]
There isn't a separate highlighting for things like `:xyz` and `'aahaha`

**Comment by xTVaser** [comment]
Can you show an example with colors / demonstrating what you want?

![image](https://user-images.githubusercontent.com/13153231/186032536-9b8ba633-c344-41a3-a423-edf5900ad9c6.png)

Keywords are tokenized separately, so they already have a separate color, this depends on your theme settings.

Quoted symbols do not (same color as normal symbols) but most lisp syntax highlighting I've seen does not colorize quoted symbols differently.

**Comment by ManDude** [comment]
![image](https://user-images.githubusercontent.com/7569514/186033999-2406e591-e9cb-46f0-872b-08a9d9bcc609.png)

Quoted symbol has the same color as non-quoted symbol, harder to notice.

As for the keys, idk I don't think I changed anything in my settings. What would I need to change?

**Comment by xTVaser** [comment]
you'd have to override your themes color settings for the `constant.keyword` textmate scope.  They are the same in the synthwave theme, colors are primarily controlled by your theme, not the extension -- it's the extensions job to tokenize the code.

the regexes around quoted expressions are non-trivial and nested.  As I said, other themes for LISPs do not seem to differentiate quoted and unquoted symbols.  They do italicize quoted s-exprs which so does our theme.  

So I'm not really interested in deviating.
